stages:
  - deploy

variables:
  NPM_MAIL: nomail@conserto.pro
  NPM_SCOPE: "@consertotech"

deploy:npm-publish:
  stage: deploy
  script:
    - apk add --update nodejs npm
    - npm install -g npm-cli-login && npm install -g npm-cli-adduser
    - npm-cli-login -u "${LYCANTHROP_NPM_USER}" -p "${LYCANTHROP_NPM_TOKEN}" -e "${NPM_MAIL}" -r "${LYCANTHROP_NPM_REPO}" -s ${NPM_SCOPE}
    - npm-cli-adduser -u "${LYCANTHROP_NPM_USER}" -p "${LYCANTHROP_NPM_TOKEN}" -e "${NPM_MAIL}" -r "${LYCANTHROP_NPM_REPO}"
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - if: '$CI_COMMIT_REF_NAME =~ "develop|main"'
      when: on_success


