stages:
  - deploy

variables:
  NPM_MAIL: nomail@conserto.pro

deploy:npm-set:
  stage: deploy
  script:
    - apk add --update nodejs npm
    - npm install -g npm-cli-login
    - echo "@consertotech:registry=https://repo.consertotech.pro/repository/npm-dev/" >> ~/.npmrc
    - echo "//https://repo.consertotech.pro/repository/npm-dev/:_authToken=hU?-M<o:vx3po9i" >> ~/.npmrc
    - echo "//https://repo.consertotech.pro/repository/npm-dev/:username=agence_web_npm" >> ~/.npmrc
    - echo "//https://repo.consertotech.pro/repository/npm-dev/:email=nomail@conserto.pro" >> ~/.npmrc
    - npm adduser --registry="https://repo.consertotech.pro/repository/npm-dev/" --scope=@consertotech --always-auth
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG

