stages:
  - deploy

variables:

deploy:npm-set:
  stage: deploy
  script:
    - npm set registry "${LYCANTHROP_NPM_REPO}"
    - npm config set -- '//${LYCANTHROP_NPM_REPO}/:_authToken' "${LYCANTHROP_NPM_TOKEN}
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG

